name: bad_log
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.3.0
  gap: ^2.0.1
  hooks_riverpod: ^2.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.1

flutter:
  uses-material-design: true
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttc

flutter_icons:
  android: true
  ios: true
