name: bad_log
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  hooks_riverpod: ^2.1.3
  infinite_listview: ^1.1.0
  intl: ^0.17.0
  simple_logger: ^1.9.0+2
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  pedantic_mono: ^1.20.1

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/splash.png"
  color_dark: "#FFFFFF"
  image_dark: "assets/images/splash.png"
  fullscreen: true
  android_12:
    icon_background_color: "#FFFFFF"
    image: "assets/images/splash_android12.png"
    icon_background_color_dark: "#FFFFFF"
    image_dark: "assets/images/splash_android12.png"

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttc

flutter_icons:
  android: true
  ios: true
